pipeline {
    agent any 
    stages {
        stage ("Pull Updates"){
            steps {
                sh "git clone https://github.com/ThomIves/Docker_Jenkins_Cloud_API.git"
            }
        }
    }
}
