pipeline {
    agent any 
    stages {
        stage ("Remove Git Directory"){
            steps {
                sh "rmdir /home/thom/Other_Git_Repos/docker-course-warp-9/My_Docker_Stuff/Docker_Jenkins_Cloud_API"
            }
        }
        stage ("Go To Git Directory"){
            steps {
                sh "cd /home/thom/Other_Git_Repos/docker-course-warp-9/My_Docker_Stuff"
            }
        }
        stage ("Clone Repo"){
            steps {
                sh "git clone https://github.com/ThomIves/Docker_Jenkins_Cloud_API.git"
            }
        }
        stage ("Report Status"){
            steps {
                echo "Updates Complete."
            }
        }
    }
}
