pipeline {
    agent any 
    stages {
        stage ("Go To Git Directory"){
            steps {
                sh "cd /home/thom/Other_Git_Repos/docker-course-warp-9/My_Docker_Stuff/Docker_Jenkins_Cloud_API"
            }
        }
        stage ("Pull Updates From Master"){
            steps {
                sh "git pull 'https://github.com/ThomIves/Docker_Jenkins_Cloud_API.git'"
            }
        }
        stage ("Report Status"){
            steps {
                echo "Updates Complete."
            }
        }
    }
}
